### ISSUE TITLE
Occasional crash on startup on modpack 

### ISSUE THREAD

**Issue by quentin452** [quentin452/ArchaicFix#3]
```
[12:55:55] [main/WARN] [mixin]: Error loading class: net/minecraft/world/biome/BiomeGenBase (java.lang.ClassNotFoundException: The specified class 'net.minecraft.world.biome.BiomeGenBase' was not found)
[12:55:55] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/GuiIngameForge
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.GuiIngameForge
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_382]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_382]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixins.archaicfix.early.json:client.core.MixinGuiIngameForge from mod archaicfix during activity: [Transform -> Method getModNameWithBiome(Lnet/minecraft/world/biome/BiomeGenBase;)Ljava/lang/String; -> GETFIELD -> net/minecraft/world/biome/BiomeGenBase::field_76791_y:Ljava/lang/String;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_382]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenBase
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_382]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenBase
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_382]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more

**Comment by quentin452** [comment]
caused by loading profiler mod

**Comment by quentin452** [comment]
i think its an issue with unimixin
